-- 코드를 입력하세요
SELECT
    a.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT a
JOIN
    FOOD_ORDER b
    ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE
    PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY
    a.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, a.PRODUCT_ID
;