-- 코드를 입력하세요
WITH BOOK_SALES_SUM AS (
    SELECT 
        BOOK_ID,
        SUM(SALES) AS TOTAL_SALES
    FROM 
        BOOK_SALES
    WHERE
        SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY
        BOOK_ID
)
SELECT
    CATEGORY,
    SUM(TOTAL_SALES) AS TOTAL_SALES
FROM
    BOOK_SALES_SUM a
JOIN
    BOOK b 
    ON a.BOOK_ID = b.BOOK_ID
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY
;